# run_robot.py
import requests
import pandas as pd
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
from config import API_KEY, EMAIL_ADDRESS, EMAIL_PASSWORD, RECEIVER_EMAIL

def fetch_weather_data(city="Helsinki"):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        weather_data = {
            "City": data["name"],
            "Temperature": data["main"]["temp"],
            "Weather": data["weather"][0]["description"],
            "Humidity": data["main"]["humidity"],
            "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        return weather_data
    else:
        print("❌ Failed to fetch weather data")
        return None

def process_data(data):
    if data:
        df = pd.DataFrame([data])
        return df
    else:
        return None

def save_to_excel(df, filename="weather_report.xlsx"):
    df.to_excel(filename, index=False)
    print(f"✅ Weather data saved to {filename}")

def send_email(city, temp):
    subject = f"Weather Report for {city}"
    body = f"The current temperature in {city} is {temp}°C.\nWeather report generated by WeatherBot."
    msg = MIMEText(body)
    msg['Subject'] = subject
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = RECEIVER_EMAIL

    try:
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        server.sendmail(EMAIL_ADDRESS, RECEIVER_EMAIL, msg.as_string())
        server.quit()
        print("📧 Email sent successfully!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

def main():
    city = "Helsinki"
    print("🤖 Running WeatherBot...")

    data = fetch_weather_data(city)
    if not data:
        print("⚠️ WeatherBot stopped due to data fetch error.")
        return

    df = process_data(data)
    if df is not None:
        save_to_excel(df)
        send_email(data["City"], data["Temperature"])
    else:
        print("⚠️ No data to process or save.")

if __name__ == "__main__":
    main()
